### ISSUE TITLE
Clarify difference between "extends" and "superclass" properties of types

### ISSUE THREAD

**Issue by felixlinker** [bpmn-io/moddle#21]
In [the documentation](https://github.com/bpmn-io/moddle/blob/master/docs/descriptor.md), there is only mentioned how to use the `superClass` property of a type. But the code and further examples relating to bpmn-js also show there is a `extends` property.

It would be great to know, how those differ as their naming is rather ambiguous.

**Comment by nikku** [comment]
`extends` is basically a mechanism to plug-in additional meta-data to known elements without modifying the existing inheritance hierarchy.

Think about it as a plug in mechanism from the side.

Instead of doing this: 

```
A
^
|
B
```

You may provide additional type information to `A` by _extending_ it with a type definition `C`:

```
A <-- C <extends>
```

This means `A` is now of type `C`, too and knows all properties of `C`.

As part of model checks you may now ask whether your dealing with `C` if you got an instance of `A` at hand: `isA(a, C) === true`.

Understandable?

**Comment by felixlinker** [comment]
Understandable! But what exactly is the difference between `extends` and `superClass` now? As far as I understand, in both cases (`B` extends `A`/`B` has-superClass `A`) `isA(b, A)` would result into `true` wouldn't it?

**Comment by nikku** [comment]
That is correct. The difference is that extending is implicit while inheriting via `superClass` is explicit.

Take the example of constructing an instance of `A`: In the `extends` case constructing `A` in the second case will give you all the properties defined in `C`, too. In the `superClass` case, you'd need to  instantiate `B` to get all the properties defined by it.

**Comment by nikku** [comment]
Feel free to ask more questions, if that helps you understand. I'll leave this issue open until we add the actual documentation for `extends`.

**Comment by felixlinker** [comment]
Ok, cool. Along with the new documentation I think I got it! Thanks for the quick response.
